src/Entity/CategoryProject.php
<?php

namespace App\Entity;

use App\Repository\CategoryProjectRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[ORM\Entity(repositoryClass: CategoryProjectRepository::class)]
#[Vich\Uploadable] 
class CategoryProject
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[Vich\UploadableField(mapping: 'categImages', fileNameProperty: 'imageName')]
    private ?File $imageFile = null;

    #[ORM\Column(type: 'string')]
    private ?string $imageName = null;

    #[ORM\OneToMany(mappedBy: 'categoryProject', targetEntity: Project::class)]
    private Collection $projects;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $CreatedAt = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $updatedAt = null;

    public function __construct()
    {
        $this->projects = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

     /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updateAt = new \DateTime();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageName(?string $imageName): void
    {
        $this->imageName = $imageName;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }




    /**
     * @return Collection<int, Project>
     */
    public function getProjects(): Collection
    {
        return $this->projects;
    }

    public function addProject(Project $project): self
    {
        if (!$this->projects->contains($project)) {
            $this->projects->add($project);
            $project->setCategoryProject($this);
        }

        return $this;
    }

    public function removeProject(Project $project): self
    {
        if ($this->projects->removeElement($project)) {
            // set the owning side to null (unless already changed)
            if ($project->getCategoryProject() === $this) {
                $project->setCategoryProject(null);
            }
        }

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->CreatedAt;
    }

    public function setCreatedAt(\DateTimeInterface $CreatedAt): self
    {
        $this->CreatedAt = $CreatedAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

}

src/Controller/Admin/AdminWebCustomPageController.php
<?php

namespace App\Controller\Admin;


use App\Entity\CustomPage;
use App\Form\CustomPageType;
use App\Repository\CustomPageRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/adminweb/custompage')]
class AdminWebCustomPageController extends AbstractController
{
    #[Route('/', name: 'app_admin_web_custom_page_index', methods: ['GET'])]
    public function index(CustomPageRepository $customPageRepository): Response
    {
        return $this->render('admin_web_custom_page/index.html.twig', [
            'custom_pages' => $customPageRepository->findAll(),
            'active' => 'custom_page'
        ]);
    }

    #[Route('/new', name: 'app_admin_web_custom_page_new', methods: ['GET', 'POST'])]
    public function new(Request $request, CustomPageRepository $customPageRepository): Response
    {
        $customPage = new CustomPage();
        $form = $this->createForm(CustomPageType::class, $customPage);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $customPageRepository->add($customPage, true);

            return $this->redirectToRoute('app_admin_web_custom_page_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('admin_web_custom_page/new.html.twig', [
            'custom_page' => $customPage,
            'form' => $form,
            'active' => 'custom_page'

        ]);
    }

    #[Route('/{id}', name: 'app_admin_web_custom_page_show', methods: ['GET'])]
    public function show(CustomPage $customPage): Response
    {
        return $this->render('admin_web_custom_page/show.html.twig', [
            'custom_page' => $customPage,
            'active' => 'custom_page'

        ]);
    }

    #[Route('/{url}', name: 'app_admin_web_custom_page_url_show', methods: ['GET'])]
    public function showSlug(CustomPage $customPage, $url): Response
    {
        return $this->render('admin_web_custom_page/show.html.twig', [
            'custom_page' => $customPage,
            'active' => 'custom_page'

        ]);
    }

    #[Route('/{id}/edit', name: 'app_admin_web_custom_page_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, CustomPage $customPage, CustomPageRepository $customPageRepository): Response
    {
        $form = $this->createForm(CustomPageType::class, $customPage);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $customPageRepository->add($customPage, true);

            return $this->redirectToRoute('app_admin_web_custom_page_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('admin_web_custom_page/edit.html.twig', [
            'custom_page' => $customPage,
            'form' => $form,
            'active' => 'custom_page'

        ]);
    }

    #[Route('/{id}', name: 'app_admin_web_custom_page_delete', methods: ['POST'])]
    public function delete(Request $request, CustomPage $customPage, CustomPageRepository $customPageRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$customPage->getId(), $request->request->get('_token'))) {
            $customPageRepository->remove($customPage, true);
        }

        return $this->redirectToRoute('app_admin_web_custom_page_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/admin_web_custom_page/_delete_form.html.twig
<form method="post" action="{{ path('app_admin_web_custom_page_delete', {'id': custom_page.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ custom_page.id) }}">
    <button class="btn">Delete</button>
</form>

templates/admin_web_custom_page/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn active">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/admin_web_custom_page/edit.html.twig
{% extends 'adminWeb.html.twig' %}

{% block title %}Edit CustomPage{% endblock %}

{% block body %}
    <h1 class="title_level_1">Edit CustomPage</h1>
    <div class="row">
        {% include "_part/asideAdmin.html.twig" %}
    {{ include('admin_web_custom_page/_form.html.twig', {'button_label': 'Update'}) }}
    <a href="{{ path('app_admin_web_custom_page_index') }}"><button class="active">Retour a la liste</button></a>
    {{ include('admin_web_custom_page/_delete_form.html.twig') }}
    </div>
{% endblock %}

templates/admin_web_custom_page/index.html.twig
{% extends 'adminWeb.html.twig' %}

{% block title %}CustomPage index{% endblock %}

{% block body %}
    <h1 class="title_level_1">CustomPage index</h1>

    <div class="row">
        {% include "_part/asideAdmin.html.twig" %}
        <table class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Title</th>
                    <th>Content</th>
                    <th>Url</th>
                    <th>CreatedAt</th>
                    <th>UpdateAt</th>
                    <th>actions</th>
                </tr>
            </thead>
            <tbody>
            {% for custom_page in custom_pages %}
                <tr>
                    <td>{{ custom_page.id }}</td>
                    <td>{{ custom_page.title }}</td>
                    <td>{{ custom_page.content }}</td>
                    <td>{{ custom_page.url }}</td>
                    <td>{{ custom_page.createdAt ? custom_page.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                    <td>{{ custom_page.updateAt ? custom_page.updateAt|date('Y-m-d H:i:s') : '' }}</td>
                    <td>
                        <div class="inline">
                            <a href="{{ path('app_admin_web_custom_page_show', {'id': custom_page.id}) }}">show</a>
                            <a href="{{ path('app_admin_web_custom_page_edit', {'id': custom_page.id}) }}">edit</a>
                        </div>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="8">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <a href="{{ path('app_admin_web_custom_page_new') }}"><button  class="active" >Créer nouveau</button></a>
{% endblock %}

templates/admin_web_custom_page/new.html.twig
{% extends 'adminWeb.html.twig' %}

{% block title %}New CustomPage{% endblock %}

{% block body %}
    <h1 class="title_level_1">Create new CustomPage</h1>
    <div class="row">
    {% include "_part/asideAdmin.html.twig" %}
    {{ include('admin_web_custom_page/_form.html.twig') }}
    </div>
    <a href="{{ path('app_admin_web_custom_page_index') }}"><button class="active">Retour a la liste</button></a>
{% endblock %}

templates/admin_web_custom_page/show.html.twig
{% extends 'adminWeb.html.twig' %}


{% block title %}CustomPage{% endblock %}

{% block body %}
    <h1 class="title_level_1">CustomPage</h1>
    <div class="row">
   {% include "_part/asideAdmin.html.twig" %}
    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ custom_page.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ custom_page.title }}</td>
            </tr>
            <tr>
                <th>Content</th>
                <td>{{ custom_page.content }}</td>
            </tr>
            <tr>
                <th>Url</th>
                <td>{{ custom_page.url }}</td>
            </tr>
            <tr>
                <th>CreatedAt</th>
                <td>{{ custom_page.createdAt ? custom_page.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>UpdateAt</th>
                <td>{{ custom_page.updateAt ? custom_page.updateAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_admin_web_custom_page_index') }}" class="active">retour a la liste</a>

    <a href="{{ path('app_admin_web_custom_page_edit', {'id': custom_page.id}) }}"class="active">édition</a>

    {{ include('admin_web_custom_page/_delete_form.html.twig') }}
{% endblock %}